doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANTE: configure a versão do seu servidor de banco (opcional)
        # server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            Event:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Event/Entity'
                prefix: 'App\Event\Entity'
                alias: Event
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/User/Entity'
                prefix: 'App\User\Entity'
                alias: User
            EventRegistration:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/EventRegistration/Entity'
                prefix: 'App\EventRegistration\Entity'
                alias: EventRegistration

        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
